[build]
# Run clippy instead of plain check on `cargo check`
# Uncomment the line below to enable this globally:
# rustc-wrapper = "clippy-driver"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]
